version: 2
jobs:
  test-golang:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/yonkornilov/snowcapper
    steps:
      - checkout
      - run: make get
      - run: make test
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/yonkornilov/snowcapper
    steps:
      - checkout
      - run: make get
      - run: make binary
      - persist_to_workspace:
          root: /go/src/github.com/yonkornilov/snowcapper
          paths:
            - snowcapper
  test-alpine:
    docker:
      - image: dockage/alpine-openrc:3.7
    steps:
      - run: apk update
      - run: apk add sudo
      - run: mkdir /run/openrc
      - run: touch /run/openrc/softlevel
      - attach_workspace:
          at: /usr/bin/
      - run: sudo snowcapper

workflows:
  version: 2
  btd:
    jobs:
      - test-golang
      - build:
          requires:
            - test-golang
      - test-alpine:
          requires:
            - build
