version: 2
jobs:
  test-golang:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/yonkornilov/snowcapper
    steps:
      - checkout
      - run: make get
      - run: make test
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/yonkornilov/snowcapper
    steps:
      - checkout
      - run: make get
      - run: make binary
      - persist_to_workspace:
          root: /go/src/github.com/yonkornilov/snowcapper
          paths:
            - snowcapper
  test-alpine:
    docker:
      - image: dockage/alpine-openrc:3.7
        command: /sbin/init
    steps:
			- run: echo "1" > /var/run/test
      - run: apk update
      - run: apk add sudo
      - attach_workspace:
          at: /usr/bin/
      - run: sudo snowcapper
      - run: sleep 3
      - run: (VAULT_ADDR=http://127.0.0.1:8200 vault status || true) 2>&1 | grep "server is not yet initialized"

workflows:
  version: 2
  btd:
    jobs:
      - test-golang
      - build:
          requires:
            - test-golang
      - test-alpine:
          requires:
            - build
