version: 2
jobs:
  fmt-test-golang:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/yonkornilov/snowcapper
    steps:
      - checkout
      - run: make get
      - run: make fmt-test
  test-golang:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/yonkornilov/snowcapper
    steps:
      - checkout
      - run: make get
      - run: make test
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/yonkornilov/snowcapper
    steps:
      - checkout
      - run: make get
      - run: make binary
      - persist_to_workspace:
          root: /go/src/github.com/yonkornilov/snowcapper
          paths:
            - snowcapper
            - examples/vim.snc
  test-alpine:
    docker:
      - image: dockage/alpine:3.8-openrc
        command: /sbin/init
    steps:
      - run: apk update
      - run: apk add sudo
      - attach_workspace:
          at: /tmp/
      - run: cp /tmp/snowcapper /usr/bin/snowcapper
      - run: sudo snowcapper
      - run: (VAULT_ADDR=http://127.0.0.1:8200 vault status || true) 2>&1 | grep "server is not yet initialized"
  coverage:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/yonkornilov/snowcapper
    steps:
      - checkout
      - run: make get
      - run: bash codecov.sh
      - run: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

workflows:
  version: 2
  btd:
    jobs:
      - fmt-test-golang
      - test-golang:
          requires:
            - fmt-test-golang
      - build:
          requires:
            - test-golang
      - test-alpine:
          requires:
            - build
      - coverage:
          requires:
            - test-alpine 
